In [2]:
import numpy as np

In [4]:
a1 = np.array([1,2,3])
a1
a1.ndim

1

In [8]:
a1.shape

(3,)

In [10]:
a2 = np.array([[1,2,3],[3,4,5]])
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
a2.ndim

2

In [12]:
a2.shape

(2, 3)

In [17]:
a3 = np.array([1,2,3.6], dtype = int)
a3

array([1, 2, 3])

In [16]:
a3.dtype

dtype('int64')

In [20]:
a4 = np.array([ ['f','l','a','k','e'],['s','n','a','k','e'],['a','w','a','k','e'] ])
a4.shape

(3, 5)

In [23]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [25]:
np.linspace(0,100,3, endpoint = False)

array([ 0.        , 33.33333333, 66.66666667])

In [38]:
x = np.array([1,'2',3])
x

array(['1', '2', '3'], dtype='<U21')

In [40]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [47]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
A*B
A.dot(B)

array([[5, 4],
       [3, 4]])

In [50]:
a = np.array([11,22])
b = np.array([18,7,6])
c = np.array([1,3,5])
d = np.concatenate((a,b,c))
d

array([11, 22, 18,  7,  6,  1,  3,  5])

In [52]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a,b), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [53]:
a = np.reshape(np.arange(12), (4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
a[0,0]

0

In [55]:
a[3,0]

9

In [56]:
a[1:3,0]

array([3, 6])

In [57]:
a[:,2]

array([ 2,  5,  8, 11])

In [58]:
a[0:4:2,0]

array([0, 6])

In [60]:
a[0,0] = 5
a

array([[ 5,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
a = np.array([1,2,3,4,5])
b = a[1:4]
b[0] = 200
a

array([  1, 200,   3,   4,   5])

In [76]:
b = np.array([[11,22], [33, 44], [55, 66]])
c = b.reshape((b.shape[0],b.shape[1],1))
c.shape

(3, 2, 1)

### 1. one-dimensional array with the numbers from 1 to 36(included)

In [82]:
a = np.arange(1,37,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

### 2. Two-dimensional array with 6 rows and 6 columns

In [83]:
a = a.reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

### 3. one-dimensional array of shape(6) containing the blue entries

In [84]:
a[:,1]

array([ 2,  8, 14, 20, 26, 32])

### 4. two-dimensional array of shape(2,2) yellow

In [92]:
a[0:2,4:6]

array([[ 5,  6],
       [11, 12]])

In [95]:
a[5,4:]

array([35, 36])

In [96]:
a[2::2, ::2]

array([[13, 15, 17],
       [25, 27, 29]])

In [3]:
a = np.reshape(np.arange(12), (4,3))

In [4]:
a>8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [6]:
a[a>8]=0

In [7]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]])

In [9]:
a = np.array([1,2,3])
a*10

array([10, 20, 30])

In [10]:
a = np.array([[1],[2], [3], [4]])
b = np.array([10, 20, 30])

In [11]:
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [13]:
np.array([[1,2,3],[4,5,6]]) + np.array([[1,2], [8,10], [3,12]])

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [17]:
dist_to_origin = [0, 1498, 1063, 1968, 1498, 1758, 
1469, 1472, 2230, 2391]
rows = np.array(dist_to_origin)
rows.shape


(10,)

In [19]:
column = rows.reshape((10,1))
column.shape

(10, 1)

In [23]:
result = np.abs(rows - column)
result

array([[   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1063,  435,    0,  905,  435,  695,  406,  409, 1167, 1328],
       [1968,  470,  905,    0,  470,  210,  499,  496,  262,  423],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1758,  260,  695,  210,  260,    0,  289,  286,  472,  633],
       [1469,   29,  406,  499,   29,  289,    0,    3,  761,  922],
       [1472,   26,  409,  496,   26,  286,    3,    0,  758,  919],
       [2230,  732, 1167,  262,  732,  472,  761,  758,    0,  161],
       [2391,  893, 1328,  423,  893,  633,  922,  919,  161,    0]])