In [21]:
import numpy as np

# Intro example

In [2]:
x = [5,7,-2,2]
y = [4,5,12,0]

In [20]:
np.array(x)*np.array(y)

array([ 20,  35, -24,   0])

# Matrices and vectors

In [4]:
A = np.array([[1,2],[2,1]])

In [5]:
B = np.array([[1,5],[0,2]])

In [6]:
A+5*B

array([[ 6, 27],
       [ 2, 11]])

In [7]:
A*B

array([[ 1, 10],
       [ 0,  2]])

In [8]:
np.dot(A,B)

array([[ 1,  9],
       [ 2, 12]])

In [11]:
a = np.array([0, 1, 2])
a

array([0, 1, 2])

In [10]:
a.T

array([0, 1, 2])

In [12]:
np.dot(a,a)

5

In [15]:
b = np.array([[0],[1],[2]])
b

array([[0],
       [1],
       [2]])

In [16]:
b.T

array([[0, 1, 2]])

In [17]:
np.dot(b,b)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [18]:
np.dot(b.T,b)

array([[5]])

In [19]:
np.dot(b,b.T)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

# Numpy broadcasting

In [22]:
a = np.array([
 [0],
 [7]
])
b = np.array([
 [1,2],
 [0,6]
])
c = np.array([
 [2,2]
])

In [24]:
a.shape

(2, 1)

In [25]:
b.shape

(2, 2)

In [26]:
c.shape

(1, 2)

In [27]:
a+c

array([[2, 2],
       [9, 9]])

In [28]:
a+b

array([[ 1,  2],
       [ 7, 13]])

In [29]:
a*b

array([[ 0,  0],
       [ 0, 42]])

# The linalg module

In [30]:
A = np.array([[3,4],[2,3]])

In [31]:
A.T

array([[3, 2],
       [4, 3]])

In [32]:
np.linalg.inv(A)

array([[ 3., -4.],
       [-2.,  3.]])

In [33]:
np.dot(A,np.linalg.inv(A))

array([[1., 0.],
       [0., 1.]])

In [34]:
np.linalg.matrix_rank(A)

2

In [36]:
B = np.array([[1,0],[0,0]])
np.linalg.inv(B) 

LinAlgError: Singular matrix

In [37]:
np.linalg.matrix_rank(B)

1

In [38]:
b=np.array([[1],[2]])

In [39]:
x=np.linalg.solve(A,b)

In [40]:
np.dot(A,x)

array([[1.],
       [2.]])

# Exercise

In [41]:
A = np.array([[2,1,1],[-5,-3,0],[1,1,-1]])

In [42]:
b = np.array([[-1],[1],[-2]])

In [43]:
np.linalg.matrix_rank(A)

3

In [44]:
A_inv = np.linalg.inv(A)