In [1]:
import numpy as np

In [2]:
x = [5,7,-2,2]
y = [4,5,12,0]

In [3]:
# Using a for loop
product = []
for i in range(len(x)):
    product.append(x[i]*y[i])
product

[20, 35, -24, 0]

In [4]:
# Linear algebra version
np.array(x)*np.array(y)

array([ 20,  35, -24,   0])

In [7]:
A = np.array([[1,2],[2,1]])
B = np.array([[1,5],[0,2]])
A+5*B

array([[ 6, 27],
       [ 2, 11]])

In [8]:
A*B

array([[ 1, 10],
       [ 0,  2]])

In [9]:
np.dot(A,B)

array([[ 1,  9],
       [ 2, 12]])

In [17]:
a = np.array([0,1,2])
a.T
np.dot(a,a)
b = np.array([[0,1,2]])
b.T.shape
b.shape

(1, 3)

In [20]:
a = np.array([[0], [7]])
b = np.array([[1,2], [0,6]])
c = np.array([[2,2]])
c.shape

(1, 2)

In [22]:
a + c

array([[2, 2],
       [9, 9]])

In [23]:
a *b

array([[ 0,  0],
       [ 0, 42]])

In [24]:
A = np.array([[3,4], [2,3]])
A.T

array([[3, 2],
       [4, 3]])

In [25]:
np.linalg.inv(A)

array([[ 3., -4.],
       [-2.,  3.]])

In [26]:
np.dot(A, np.linalg.inv(A))

array([[1., 0.],
       [0., 1.]])

In [27]:
np.linalg.matrix_rank(A)

2

In [28]:
B = np.array([[1,0],[0,0]])
np.linalg.inv(B)

LinAlgError: Singular matrix

In [29]:
b = np.array([1,2])
x = np.linalg.solve(A,b)
x

array([-5.,  4.])

In [30]:
np.dot(A,x)

array([1., 2.])

In [40]:
#1
A = np.array([[2,1,1], [-5,-3,0], [1,1,-1]])
b = np.array([[-1],[1],[-2]])
#2
np.linalg.matrix_rank(A)
#3
np.linalg.inv(A)
#4
x = np.dot(np.linalg.inv(A), b)
x
#5
x = np.linalg.solve(A,b)
x
#6


array([[  7.],
       [-12.],
       [ -3.]])